### ISSUE TITLE
Cannot commit to other repo

### ISSUE THREAD

**Issue by lukethecoder64** [abadami/team6412#2]
Andrew,

I cannot commit to the real ftc repo (https://github.com/abadami/ftc_app). When I try to edit the readme on the web editor it creates a fork and then I edit/commit to that fork. Also, when I try to commit from Andriod Studio, I get a 403 Access Denied. I'd assume this is something the repo "owner" (you) can change. Could you, if you can?

P.S. You can delete this repo. Theres nothing in it.

**Comment by abadami** [comment]
Check it now, I forgot to note you as a collaborator.  Let me know if you get it.  I'm not sure about the fork, but see if giving you access helps the whole situation.

**Comment by lukethecoder64** [comment]
There we go. Thanks!
